\version: '3.8'
services:
  springboot:
    image: dockerguruprasanna/spring-boot-mongo:latest
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: springboot
    environment:
    - MONGO_DB_HOSTNAME=mongo
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    networks:
    - springappbridge

  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappbridge

volumes:
  mongodb:
    external: true

networks:
  springappbridge:
    external: true
